# Generated by Django 3.2.7 on 2021-09-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('gender_preference', models.CharField(max_length=50)),
                ('likes', models.IntegerField()),
                ('match_id', models.CharField(max_length=50)),
                ('interests', models.CharField(max_length=50)),
                ('food_preferences', models.CharField(max_length=50)),
                ('music_preferences', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
            ],
        ),
    ]
