# Generated by Django 3.2.7 on 2021-09-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FriendApp', '0002_dislikes_likes_location_match_pictures_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='food_preferences',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender_preference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='music_preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
