# Generated by Django 3.2.7 on 2021-09-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FriendApp', '0004_remove_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='profile_pics', verbose_name='default.jpg')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FriendApp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
